server:
  port: 9092



spring:
  profiles:
    active: dev
  application:
    name: FOODCATOLOG-SERVICE

  datasource:


    driver-class-name: com.mysql.cj.jdbc.Driver  # optional; Boot can infer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect