
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



  datasource:
    url: jdbc:mysql://localhost:3306/dbfood
    username: "root"
    password: "Phanindra@123"   # or root, whatever you actually use

    driver-class-name: com.mysql.cj.jdbc.Driver  # optional; Boot can infer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect